name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TESTING: "true"
      PYTEST_CURRENT_TEST: "1"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/test_simple.py -v

      # Slack notification for test results
      - name: Slack Notification - Tests Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: "#ci-cd"
          text: "🔴 Tests failed for ${{ github.repository }} on branch ${{ github.ref_name }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack Notification - Tests Passed
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: "#ci-cd"
          text: "✅ Tests passed for ${{ github.repository }} on branch ${{ github.ref_name }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/socials:latest

      # Slack notification for deployment
      - name: Slack Notification - Deployment Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: "#deployments"
          text: "🚀 Successfully built and pushed Docker image for ${{ github.repository }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack Notification - Deployment Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: "#deployments"
          text: "❌ Docker build/push failed for ${{ github.repository }}. Please check the logs."
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy-to-render:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

      - name: Slack Notification - Render Deployment Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: "#deployments"
          text: "🚀 Successfully triggered deployment to Render.com for ${{ github.repository }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack Notification - Render Deployment Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: "#social_app_cicd"
          text: "❌ Failed to trigger Render deployment for ${{ github.repository }}. Please check the logs."
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # Notify on workflow completion
  notify:
    runs-on: ubuntu-latest
    needs: [test, build-and-push, deploy-to-render]
    if: always()
    steps:
      - name: Slack Notification - Workflow Summary
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: "#social_app_cicd"
          fields: repo,message,commit,author,action,eventName,ref,workflow
          text: |
            Workflow completed for *${{ github.repository }}*

            📊 *Summary:*
            • Tests: ${{ needs.test.result }}
            • Docker Build: ${{ needs.build-and-push.result }}
            • Render Deploy: ${{ needs.deploy-to-render.result }}
            • Triggered by: ${{ github.actor }}
            • Branch: ${{ github.ref_name }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
